### ISSUE TITLE
sort eigen values

### ISSUE THREAD

**Issue by rcprati** [crcollins/molml#1]
Hi,

the numpy method for calculating eigenvalues does not sort them
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html

should the eigenvalues of the Coulomb matrix be sorted?

**Comment by crcollins** [comment]
Haha, yeah, the values should be sorted. I think I had that API mixed up with one that returned sorted values. Adding a fix now.

**Comment by crcollins** [comment]
This is now fixed with 9a38963a.
